 export function generateText(rows: Number) : String {

    let list = getPersonList();

    if (rows < list.size) list = list.subarray(0, rows - 1)

     else {
         for (let i = 0; i < rows / 250 - 1; i++){
             list = list.concat(getPersonList());
         }
    }

    let text = "";

    list.forEach( person => {

        let newText = person.name + "," + person.surname + "\n";
        text += newText;
    });

    return text.substr(0, text.length - 2)
 }


export function getPersonList() {
    return [
    {name: "Renae",     surname: "Mays"},
    {name: "Alistair",  surname: "Southern"},
    {name: "Elowen",    surname: "Hook"},
    {name: "Lily-Rose", surname: "Mcknight"},
    {name: "Hermione",  surname: "Hamer"},
    {name: "Faizaan",   surname: "Hackett"},
    {name: "Eesha",     surname: "Wolfe"},
    {name: "Xavier",    surname: "Hewitt"},
    {name: "Joyce",     surname: "Thompson"},
    {name: "Marshall",  surname: "Storey"},
    {name: "Aneeka",    surname: "Knights"},
    {name: "Clyde",     surname: "Holt"},
    {name: "Huzaifah",  surname: "Chandler"},
    {name: "Lynda",     surname: "Mullins"},
    {name: "Herbert",   surname: "Fry"},
    {name: "Curtis",    surname: "Haines"},
    {name: "Bethan",    surname: "Naylor"},
    {name: "Jokubas",   surname: "Easton"},
    {name: "Alyce",     surname: "Adamson"},
    {name: "Priya",     surname: "Frye"},
    {name: "Ayah",      surname: "Dodd"},
    {name: "Judah",     surname: "Rasmussen"},
    {name: "Harvie",    surname: "Dale"},
    {name: "Peter",     surname: "Hahn"},
    {name: "Rebecca",   surname: "Bowers"},
    {name: "Patsy",     surname: "Bone"},
    {name: "Abdurahman",surname: "Person"},
    {name: "Charleigh", surname: "Potter"},
    {name: "Serenity",  surname: "Montes"},
    {name: "Rhia",      surname: "Greer"},
    {name: "Ursula",    surname: "Guy"},
    {name: "Abby",      surname: "Collier"},
    {name: "Lex",       surname: "Juarez"},
    {name: "Abid",      surname: "Combs"},
    {name: "Angela",    surname: "Monroe"},
    {name: "Saul",      surname: "Costa"},
    {name: "Jimi",      surname: "Sellers"},
    {name: "Kennedy",   surname: "O'Ryan"},
    {name: "Izabel",    surname: "Garza"},
    {name: "Teresa",    surname: "Ponce"},
    {name: "Khalil",    surname: "Kirk"},
    {name: "Amal",      surname: "Witt"},
    {name: "Emil",      surname: "Portillo"},
    {name: "Umaiza",    surname: "Vasquez"},
    {name: "Filip",     surname: "Guevara"},
    {name: "Dominick",  surname: "Sanderson"},
    {name: "Paul",      surname: "James"},
    {name: "Austin",    surname: "Conway"},
    {name: "Bronwen",   surname: "Talbot"},
    {name: "Riaz",      surname: "Huff"},
    {name: "Dollie",    surname: "Glenn"},
    {name: "Harriet",   surname: "Hill"},
    {name: "Tamara",    surname: "Baker"},
    {name: "Kali",      surname: "Werner"},
    {name: "Momina",    surname: "Alvarez"},
    {name: "Verity",    surname: "Contreras"},
    {name: "Zacharias", surname: "Leech"},
    {name: "Mariyah",   surname: "Payne"},
    {name: "Milo",      surname: "Morton"},
    {name: "Sayed",     surname: "Bernal"},
    {name: "Ethan",     surname: "Perry"},
    {name: "Hamish",    surname: "Guest"},
    {name: "Mercedes",  surname: "Dolan"},
    {name: "Shanice",   surname: "Corrigan"},
    {name: "Antoine",   surname: "Woodley"},
    {name: "Sachin",    surname: "Newman"},
    {name: "Julie",     surname: "Garcia"},
    {name: "Asiyah",    surname: "Roman"},
    {name: "Steve",     surname: "Chung"},
    {name: "Keeva",     surname: "Summers"},
    {name: "Nicole",    surname: "Doherty"},
    {name: "Cecily",    surname: "Wainwright"},
    {name: "Osman",     surname: "Searle"},
    {name: "Samiya",    surname: "Keenan"},
    {name: "Carl",      surname: "Suarez"},
    {name: "Marcelina", surname: "Crawford"},
    {name: "Enrique",   surname: "Smart"},
    {name: "Marius",    surname: "Bautista"},
    {name: "Sid",       surname: "Winters"},
    {name: "Arun",      surname: "Meadows"},
    {name: "Adrian",    surname: "Maynard"},
    {name: "Kealan",    surname: "Carver"},
    {name: "Kayan",     surname: "Bailey"},
    {name: "Roxie",     surname: "Hail"},
    {name: "Tayyab",    surname: "Avery"},
    {name: "Kelsi",     surname: "Gates"},
    {name: "Suraj",     surname: "Magana"},
    {name: "Brian",     surname: "Oliver"},
    {name: "Sadiyah",   surname: "Villanueva"},
    {name: "Iga",       surname: "Ali"},
    {name: "Clifford",  surname: "Coulson"},
    {name: "Manha",     surname: "Wills"},
    {name: "Harlee",    surname: "Brooks"},
    {name: "Muhammed",  surname: "Deleon"},
    {name: "Menaal",    surname: "Ingram"},
    {name: "Mia",       surname: "Pratt"},
    {name: "Conna",     surname: "Casey"},
    {name: "Kris",      surname: "Martins"},
    {name: "Reegan",    surname: "Tyler"},
    {name: "Blessing",  surname: "Rutledge"},
    {name: "Chester",   surname: "Fountain"},
    {name: "Mischa",    surname: "Preece"},
    {name: "Ottilie",   surname: "Croft"},
    {name: "Jarred",    surname: "Grant"},
    {name: "Delia",     surname: "Mcfarlane"},
    {name: "Findlay",   surname: "Mcgill"},
    {name: "Rufus",     surname: "Wyatt"},
    {name: "Maddy",     surname: "Sweet"},
    {name: "Jordanna",  surname: "Busby"},
    {name: "Sachin",    surname: "Higgins"},
    {name: "Fionn",     surname: "Esparza"},
    {name: "Eden",      surname: "Mullins"},
    {name: "Ranveer",   surname: "Gallagher"},
    {name: "Ihsan",     surname: "Corona"},
    {name: "Susan",     surname: "Connelly"},
    {name: "Ben",       surname: "Ochoa"},
    {name: "Arianne",   surname: "Frey"},
    {name: "Yash",      surname: "Barclay"},
    {name: "Ashleigh",  surname: "Nixon"},
    {name: "Vincent",   surname: "Moody"},
    {name: "Mimi",      surname: "Bevan"},
    {name: "Selina",    surname: "Byrd"},
    {name: "Humera",    surname: "Curry"},
    {name: "Saba",      surname: "Knowles"},
    {name: "Mea",       surname: "Reader"},
    {name: "Judith",    surname: "Mays"},
    {name: "Roberto",   surname: "Southern"},
    {name: "Kenan",     surname: "Hook"},
    {name: "Giselle",   surname: "Mcknight"},
    {name: "Dominic",   surname: "Hamer"},
    {name: "Ela-Louise",surname: "Hackett"},
    {name: "Abubakar",  surname: "Wolfe"},
    {name: "Selena",    surname: "Hewitt"},
    {name: "Talha",     surname: "Thompson"},
    {name: "Shanai",    surname: "Storey"},
    {name: "Alissa",    surname: "Knights"},
    {name: "John-James",surname: "Holt"},
    {name: "Reece",     surname: "Chandler"},
    {name: "Primrose",  surname: "Mullins"},
    {name: "Pascal",    surname: "Fry"},
    {name: "Safah",     surname: "Haines"},
    {name: "Laylah",    surname: "Naylor"},
    {name: "Willow",    surname: "Easton"},
    {name: "Taslima",   surname: "Adamson"},
    {name: "Una",       surname: "Frye"},
    {name: "Miley",     surname: "Dodd"},
    {name: "Zakaria",   surname: "Rasmussen"},
    {name: "Warren",    surname: "Dale"},
    {name: "Constance", surname: "Hahn"},
    {name: "Sakina",    surname: "Bowers"},
    {name: "Carly",     surname: "Bone"},
    {name: "Fenton",    surname: "Person"},
    {name: "Nahla",     surname: "Potter"},
    {name: "Joel",      surname: "Montes"},
    {name: "Pia",       surname: "Greer"},
    {name: "Kayden",    surname: "Guy"},
    {name: "Anja",      surname: "Collier"},
    {name: "Kingsley",  surname: "Juarez"},
    {name: "Phillippa", surname: "Combs"},
    {name: "Alayah",    surname: "Monroe"},
    {name: "Rebecca",   surname: "Costa"},
    {name: "Malakai",   surname: "Sellers"},
    {name: "Ubaid",     surname: "O'Ryan"},
    {name: "Naeem",     surname: "Garza"},
    {name: "Jim",       surname: "Ponce"},
    {name: "Menachem",  surname: "Kirk"},
    {name: "Aedan",     surname: "Witt"},
    {name: "Dougie",    surname: "Portillo"},
    {name: "Destiny",   surname: "Vasquez"},
    {name: "Amara",     surname: "Guevara"},
    {name: "Gracie",    surname: "Sanderson"},
    {name: "Mara",      surname: "James"},
    {name: "Aayush",    surname: "Conway"},
    {name: "Elysha",    surname: "Talbot"},
    {name: "Juno",      surname: "Huff"},
    {name: "Nigel",     surname: "Glenn"},
    {name: "Kathleen",  surname: "Hill"},
    {name: "Evie-Grace",surname: "Baker"},
    {name: "Dione",     surname: "Werner"},
    {name: "Ameera",    surname: "Alvarez"},
    {name: "Wade",      surname: "Contreras"},
    {name: "James",     surname: "Leech"},
    {name: "Steven",    surname: "Payne"},
    {name: "Iqra",      surname: "Morton"},
    {name: "Emmanuel",  surname: "Bernal"},
    {name: "Kelis",     surname: "Perry"},
    {name: "Ian",       surname: "Guest"},
    {name: "Mackenzie", surname: "Dolan"},
    {name: "Eve",       surname: "Corrigan"},
    {name: "Freddie",   surname: "Woodley"},
    {name: "Petra",     surname: "Newman"},
    {name: "Nikhil",    surname: "Garcia"},
    {name: "Kaitlan",   surname: "Roman"},
    {name: "Moesha",    surname: "Chung"},
    {name: "Julius",    surname: "Summers"},
    {name: "Arjun",     surname: "Doherty"},
    {name: "Rachelle",  surname: "Wainwright"},
    {name: "Nawal",     surname: "Searle"},
    {name: "Brodie",    surname: "Keenan"},
    {name: "Sahib",     surname: "Suarez"},
    {name: "Tayla",     surname: "Crawford"},
    {name: "Ammaar",    surname: "Smart"},
    {name: "Rico",      surname: "Bautista"},
    {name: "Scarlette", surname: "Winters"},
    {name: "Kelsi",     surname: "Meadows"},
    {name: "Chyna",     surname: "Maynard"},
    {name: "Marlon",    surname: "Carver"},
    {name: "Magdalena", surname: "Bailey"},
    {name: "Azaan",     surname: "Hail"},
    {name: "Rivka",     surname: "Avery"},
    {name: "Aislinn",   surname: "Gates"},
    {name: "Roshan",    surname: "Magana"},
    {name: "Patience",  surname: "Oliver"},
    {name: "Shah",      surname: "Villanueva"},
    {name: "Coby",      surname: "Ali"},
    {name: "Anisa",     surname: "Coulson"},
    {name: "Hilary",    surname: "Wills"},
    {name: "Tymoteusz", surname: "Brooks"},
    {name: "Kaila",     surname: "Deleon"},
    {name: "Tania",     surname: "Ingram"},
    {name: "Marlene",   surname: "Pratt"},
    {name: "Lucie",     surname: "Casey"},
    {name: "Myra",      surname: "Martins"},
    {name: "Zander",    surname: "Tyler"},
    {name: "Lianne",    surname: "Rutledge"},
    {name: "Robyn",     surname: "Fountain"},
    {name: "Akash",     surname: "Preece"},
    {name: "Willem",    surname: "Croft"},
    {name: "Caius",     surname: "Grant"},
    {name: "Aleksander",surname: "Mcfarlane"},
    {name: "Jagdeep",   surname: "Mcgill"},
    {name: "Divine",    surname: "Wyatt"},
    {name: "Rahim",     surname: "Sweet"},
    {name: "Aine",      surname: "Busby"},
    {name: "Patrycja",  surname: "Higgins"},
    {name: "Savanna",   surname: "Esparza"},
    {name: "Sommer",    surname: "Mullins"},
    {name: "Jamila",    surname: "Gallagher"},
    {name: "Gary",      surname: "Corona"},
    {name: "Naomi",     surname: "Connelly"},
    {name: "Laurence",  surname: "Ochoa"},
    {name: "Fatima",    surname: "Frey"},
    {name: "Carolyn",   surname: "Barclay"},
    {name: "Alice",     surname: "Nixon"},
    {name: "Ishan",     surname: "Moody"},
    {name: "Liya",      surname: "Bevan"},
    {name: "Nancy",     surname: "Byrd"},
    {name: "Grayson",   surname: "Curry"},
    {name: "Ariella",   surname: "Knowles"},
    {name: "Mirza",     surname: "Reader"}
    ]
}

